name: Deploy Laravel Otomatis

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # =========================
      # ZIP BACKEND
      # =========================
      - name: Buat ZIP Backend
        run: |
          zip -q -r deploy.zip . \
          -x "*.git*" \
          -x "vendor/*" \
          -x "node_modules/*" \
          -x "public/*" \
          -x ".env" \
          -x "bootstrap/cache/*"

      - name: Upload Backend ZIP
        run: |
          curl --ftp-create-dirs \
          -T deploy.zip \
          ftp://${{ secrets.FTP_SERVER }}/deploy.zip \
          --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"

      # =========================
      # ZIP FRONTEND
      # =========================
      - name: Buat ZIP Frontend
        run: |
          cd public
          zip -q -r ../public.zip . -x "assets/modules/*"
          cd ..

      - name: Upload Frontend ZIP
        run: |
          curl --ftp-create-dirs \
          -T public.zip \
          ftp://${{ secrets.FTP_SERVER }}/public_html/public.zip \
          --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"